---
- name: Config Internet router
  hosts: all
  become: yes
  gather_facts: no
  vars:

  tasks:
    - name: Include basic tasks for router
      ansible.builtin.include_tasks: routerBasicConf.yml

    - name: Add internal routes
      ansible.builtin.lineinfile:
        path: /etc/network/interfaces
        line: 'up {{item}}'
      loop:
        - sleep 5
        - ip r a 192.168.0.0/22 via 192.168.255.2
        - ip r a 192.168.255.8/30 via 192.168.255.2
        - ip r a 192.168.255.4/30 via 192.168.255.2
        - iptables -A POSTROUTING -t nat -o eth0 -s 192.168.0.0/16 -j MASQUERADE

          #    - name: Add rule for NAT
          #      ansible.builtin.iptables:
          #        chain: POSTROUTING
          #        table: nat
          #        out_interface: eth0
          #        source: 192.168.0.0/255.255.0.0
          #        to_source: 10.0.2.15
          #        jump: SNAT

    - name: reboot system
      ansible.builtin.reboot:
        connect_timeout: 30
