---
- name: Config Internet router
  hosts: all
  become: yes
  gather_facts: no
  vars:

  tasks:
    - name: Include basic tasks for router
      ansible.builtin.include_tasks: routerBasicConf.yml

    - name: Add internal routes
      ansible.builtin.lineinfile:
        path: /etc/network/interfaces
        line: 'up {{item}}'
      loop:
        - sleep 5
        - ip r d default via 10.0.2.2
        - ip r a default via 192.168.255.5

    - name: reboot system
      ansible.builtin.reboot:
        connect_timeout: 30

